version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - mysql
    ports:
      - 8888:80
    volumes:
      - .:/srv/app
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=turbo
volumes:
  mysql:
    driver: local

